# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('creacion', models.IntegerField(default=0)),
                ('historia', models.CharField(max_length=1000)),
                ('entrenador', models.CharField(max_length=50)),
                ('escudo', models.ImageField(upload_to=b'')),
                ('estadio', models.CharField(max_length=50)),
                ('puntos', models.IntegerField(default=0)),
                ('golesAfavor', models.IntegerField(default=0)),
                ('golesenContra', models.IntegerField(default=0)),
                ('partidosJugados', models.IntegerField(default=0)),
                ('partidosGanados', models.IntegerField(default=0)),
                ('partidosPerdidos', models.IntegerField(default=0)),
                ('partidosEmpatados', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('dorsal', models.IntegerField(default=0)),
                ('nacimiento', models.DateField()),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('amarillas', models.IntegerField(default=0)),
                ('rojas', models.IntegerField(default=0)),
                ('posicion', models.CharField(choices=[(b'Delantero', b'Delantero'), (b'Centrocampista', b'Centrocampista'), (b'Defensa', b'Defensa'), (b'Portero', b'Portero')], max_length=30)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga.Equipo')),
            ],
        ),
    ]
