# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[(b'En juego', b'En juego'), (b'Finalizado', b'Finalizado'), (b'Sin comenzar', b'Sin comenzar')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='creacion',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipoLocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='Liga.Equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipoVisitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitante', to='Liga.Equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Liga.Jornada'),
        ),
    ]
