# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0003_auto_20161204_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='nombreequipo',
            new_name='nombreEquipo',
        ),
        migrations.AlterField(
            model_name='jornada',
            name='numJornada',
            field=models.CharField(max_length=50),
        ),
    ]
