# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0004_auto_20161210_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='nombreUrl',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
