# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0006_jornada_nombreurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='nombreUrl',
        ),
    ]
