# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0008_auto_20161210_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='estadio',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
