# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0009_partido_estadio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='jornada',
        ),
    ]
