# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0011_partido_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='numJornada',
            field=models.CharField(max_length=50),
        ),
    ]
