# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0012_auto_20161210_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombreUrl',
        ),
    ]
