# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0013_remove_equipo_nombreurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='numJornada',
            field=models.IntegerField(default=0),
        ),
    ]
